<?php
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id .= $this->publicationId.'_'.$this->zoneconfig['conf']['id'];
    }
?>
<h1 id="<?= $id ?>" data-melisKey="<?= $this->melisKey; ?>" class="content-heading"> <?= ($this->publicationId) ? $this->translate($this->zoneconfig['conf']['name']).' '.$this->publicationName : $this->translate('tr_publications_list_header_title_new') ?></h1>
<p><?= $this->translate('tr_publications_header_title_description'); ?></p>